### ISSUE TITLE
Custom Mapping

### ISSUE THREAD

**Issue by ShahramNo** [babaktaremi/Clean-Architecture-Template#9] opened 2023-05-03 10:22 UTC
hi, thanks for your shared repo, it's exellent,
how can i use custom mapping?

**Comment by ShahramNo** [comment] 2023-05-03 13:26
i change in my project myself:
public interface ICreateMapper<TSource>
{
    void Map(Profile profile)
    {
        profile.CreateMap(typeof(TSource), GetType()).ReverseMap();
        ConfigureCustomMappings(profile); // Call method to configure custom mappings

    }
    void ConfigureCustomMappings(Profile profile);

}
public class RegisterMapper:Profile
{
    public RegisterMapper()
    {
        this.ApplyMappingProfiles(Assembly.GetExecutingAssembly());
    }


    private void ApplyMappingProfiles(Assembly assembly)
    {
        var types = assembly.GetExportedTypes().Where(t => t.GetInterfaces().Any(i =>
                i.IsGenericType && i.GetGenericTypeDefinition() == typeof(ICreateMapper<>)))
            .ToList();

        foreach (var type in types)
        {
            var model = Activator.CreateInstance(type);

            var methodInfo = type.GetMethod("Map"); // Get the Map method directly by the class

            if (model != null)
            {
                methodInfo?.Invoke(model, new object[] { this });

                var configureCustomMappingsMethod = type.GetMethod("ConfigureCustomMappings");

                if (configureCustomMappingsMethod != null)
                {
                    configureCustomMappingsMethod.Invoke(model, new object[] { this });
                }
            }
        }
    }
}
and then when i inherit  ICreateMapper<model>
public class SampleQueryResult : ICreateMapper<Model>
{
    public string LicenseStatus { get; set; }

  //...
 public void ConfigureCustomMappings(Profile profile)
    {
        profile
            .CreateMap<Model, SampleQueryResult >()
            .ForMember(
                dest => dest.LicenseStatus,
                config =>
                    config.MapFrom(src => $"{src.LicenseStatus.ToDisplay(DisplayProperty.Name)}"));
    }
}

**Comment by babaktaremi** [comment] 2023-05-21 13:04
Sorry. Been pretty busy these two weeks.

You Don't Need To Extend The Interface . Since C# 8 Interfaces can have default implementations. Just override ```map``` method from ```ICreateMapper``` interface. Your code would be like:

```C#
public class SampleQueryResult : ICreateMapper<SimpleQueryDto> // assuming your target model is SimpleQueryDto
    {
        public string LicenseStatus { get; set; }

        //...
        public void Map(AutoMapper.Profile profile)
        {
            profile
                .CreateMap<SimpleQueryDto, SampleQueryResult>()
                .ForMember(
                    dest => dest.LicenseStatus,
                    config =>
                        config.MapFrom(src => $"{src.LicenseStatus.ToDisplay(DisplayProperty.Name)}"));
        }
    }

```

**Comment by ShahramNo** [comment] 2023-05-21 13:10
> Sorry. Been pretty busy these two weeks.
> 
> You Don't Need To Extend The Interface . Since C# 8 Interfaces can have default implementations. Just override `map` method from `ICreateMapper` interface. Your code would be like:
> 
> ```cs
> public class SampleQueryResult : ICreateMapper<SimpleQueryDto> // assuming your target model is SimpleQueryDto
>     {
>         public string LicenseStatus { get; set; }
> 
>         //...
>         public void Map(AutoMapper.Profile profile)
>         {
>             profile
>                 .CreateMap<SimpleQueryDto, SampleQueryResult>()
>                 .ForMember(
>                     dest => dest.LicenseStatus,
>                     config =>
>                         config.MapFrom(src => $"{src.LicenseStatus.ToDisplay(DisplayProperty.Name)}"));
>         }
>     }
> ```

You're welcome!  And thank you for expressing your gratitude.
Regarding your response, I see that you have provided a code snippet related to mapping in AutoMapper. It seems that you are suggesting an alternative approach for mapping in your scenario.
Overall, your suggestion provides a concise and straightforward way to define and manage the mapping configuration for your scenario. Thank you for sharing it!

**Comment by babaktaremi** [comment] 2023-05-22 08:06
> > Sorry. Been pretty busy these two weeks.
> > You Don't Need To Extend The Interface . Since C# 8 Interfaces can have default implementations. Just override `map` method from `ICreateMapper` interface. Your code would be like:
> > ```cs
> > public class SampleQueryResult : ICreateMapper<SimpleQueryDto> // assuming your target model is SimpleQueryDto
> >     {
> >         public string LicenseStatus { get; set; }
> > 
> >         //...
> >         public void Map(AutoMapper.Profile profile)
> >         {
> >             profile
> >                 .CreateMap<SimpleQueryDto, SampleQueryResult>()
> >                 .ForMember(
> >                     dest => dest.LicenseStatus,
> >                     config =>
> >                         config.MapFrom(src => $"{src.LicenseStatus.ToDisplay(DisplayProperty.Name)}"));
> >         }
> >     }
> > ```
> 
> You're welcome! And thank you for expressing your gratitude. Regarding your response, I see that you have provided a code snippet related to mapping in AutoMapper. It seems that you are suggesting an alternative approach for mapping in your scenario. Overall, your suggestion provides a concise and straightforward way to define and manage the mapping configuration for your scenario. Thank you for sharing it!

You're welcome!. Seems that the problem is solved. Closing the issue. Feel free to reopen it if you encounter similar problem

**Closed by babaktaremi** 2023-05-22 08:06 UTC
